### ISSUE TITLE
Running dev script requires running two terminals

### ISSUE THREAD

**Issue by kriswuollett** [antoniolofiego/Batteries-Included-Next.js#3]
Since `tailwindcss` is running in `jit` mode, a `postcss` process needs to be running in `watch` mode in parallel with `next dev`. Since the `dev` script currently may not be directly compatible with Windows developers anyways, why not simplify `dev` for Unix-like developers? I think running `postcss` in the background should be possible.

**Comment by antoniolofiego** [comment]
Solved by #8
